### ISSUE TITLE
Add More Items to set_state()

### ISSUE THREAD

**Issue by davedavis** [nirantak/hue-api#8]
Hi Nirantak,
Thanks so much for such a well written library and for keeping it up to date. 

I was wondering if you had any plans to add the rest of the available states to the set_state() Light method?
Your library is amazing, but only supports a small number of state changes. I'd love to allow for effects, alert and colormode. 

Is this something you'd be interested in adding? If not, can you tell me what the best way to go about it is? Is it as simple as adding the required keys in the method on line 101?

Many thanks again for all the time you put into this (and for the type hints).

**Comment by nirantak** [comment]
Hi @davedavis, thanks for using this!
The addition of the remaining attributes would involve updating that one method only, I can add them based on the ones listed here https://developers.meethue.com/develop/hue-api/lights-api/#set-light-state

**Comment by nirantak** [comment]
Hey @davedavis, I have added the options, you can update to version 0.4.7 to use it.
Code change here https://github.com/nirantak/hue-api/commit/b10e456d0e3138057e6de10955082a71c0c6c9d0
